### ISSUE TITLE
Serving Static Files

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-routing#11]
Hi!
I think that you need to specify in README that the handler for serving static files must be the latest handler in the routing tree.

**Comment by qiangxue** [comment]
Not necessarily so. The key is the following highlighted sentence in README:

    If an incoming request matches multiple routes in the table, the route added first to the table will take precedence. All other matching routes will be ignored.

**Comment by SpencerDawson** [comment]
So a quick question on this. If I have an app directory somewhere else on the system, I can serve an index file with an absolute path, but when serving static files in a directory, if I pass it an absolute path, it gets appended to the working directory of the go application.

example:

```
handler := http.NewServeMux()
router  := routing.New()
dist    := "/absolute/path/to/dist/"
index   := dist+"index.html"

router.Get("/", file.Content(index))
router.Get("/*", file.Server(file.PathMap{
    "/": outDist,
}))

handler.Handle("/", router)
http.ListenAndServe(":8080", handler)
```

I am getting index served at localhost:8080, but index cannot GET styles.css at localhost:8080/assets/styles.css, it's trying to serve a file from `/absolute/path/to/src/domain/user/project/absolute/path/to/dist/assets/styles.css` instead of `/absolute/path/to/dist/assets/styles.css`.

If I have the application directory installed in the root of my go project, it works fine, but I seem to be unable to get any files when attempting to serve from a directory beyond the go projects root directory.

**Comment by qiangxue** [comment]
In this case, when calling `file.Server()` you should specify `ServerOptions.RootPath` in its second parameter. Otherwise it will default to the current working path.

**Comment by SpencerDawson** [comment]
I was just going through the source again and noticed it. I appreciate the quick reply and clarification.
