### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by valyala** [go-ozzo/ozzo-routing#14]
It would be great adding support for [fasthttp](https://github.com/valyala/fasthttp) in ozzo-routing. Fasthttp is extremely fast and it doesn't allocate memory in fast paths. So fasthttp-backed ozzo-routing will allow writing low-overhead http servers with advanced routing capabilities.

**Comment by qiangxue** [comment]
fasthttp looks very impressive! 

Creating a fasthttp ozzo router won't involve much work. We do need to create a separate package to do this though due to the incompatibility between fasthttp and net/http.

Do you have any plan/idea on how to adapt net/http handlers to fasthttp ones? I think one major advantage of net/http is that it has a lot of existing handlers/middlewares.

I noticed that `fasthttp.RequestCtx` contains Response struct rather than interface. This makes it impossible to extend Response in middlewares and custom applications. Do you have a solution for this?

**Comment by qiangxue** [comment]
Here is an initial implementation: https://github.com/qiangxue/fasthttp-routing

**Comment by valyala** [comment]
> Do you have any plan/idea on how to adapt net/http handlers to fasthttp ones?

There is [fasthttpadaptor](https://godoc.org/github.com/valyala/fasthttp/fasthttpadaptor) for converting net/http handlers to fasthttp ones. But it slows down the resulting code, since the conversion requires multiple memory allocations and copies.

**Comment by valyala** [comment]
Just mentioned [fasthttp-routing](https://github.com/qiangxue/fasthttp-routing) in fasthttp README - see https://github.com/valyala/fasthttp/commit/da0d6f1ea7da6384bf5bc859c9e317feea5b727a

**Comment by qiangxue** [comment]
Thanks! Is there something similar to `httptest.ResponseRecorder` in fasthttp? This is very useful when writing unit tests.

**Comment by valyala** [comment]
> Thanks! Is there something similar to httptest.ResponseRecorder in fasthttp

No. But take a look at [fasthttputil](https://godoc.org/github.com/valyala/fasthttp/fasthttputil), which I use for fasthttp client-server tests. See examples at [server_test.go](https://github.com/valyala/fasthttp/blob/master/server_test.go).
