### ISSUE TITLE
Further development of ozzo framework

### ISSUE THREAD

**Issue by mistbow-git** [go-ozzo/ozzo-routing#3]
Qiang, do you plan to develop ozzo like yii in the future? I like yii, but I think that my new project is to big for yii.
I would like to start developing a big project on golang using ozzo right now.)
But I would like to understand the perspectives...

**Comment by qiangxue** [comment]
Yes, I will continue spending time developing ozzo. But it won't be like yii in the sense that ozzo will be a loosely coupled collection of packages so that you can pick up the ones you need in your project. 

My initial plan for ozzo are along these areas:

* the foundational packages, including config, logging, di, caching (TBD), etc.
* REST API support (routing is done)
* DB support (just finished DB abstraction layer and query builder)
* boilerplates

I think as a language, golang can do a lot more things than PHP. I will also try doing some other interesting work in go.

You are very welcome to use ozzo or even contribute to ozzo.

**Comment by mistbow-git** [comment]
I think it is right!. Yii is not a true golang way.))

**Comment by su-xiaolin** [comment]
What is greater between yii coupled components and go-ozzo loosely coupled components? What is your opioin @qiangxue

**Comment by qiangxue** [comment]
This is a big topic. :)

IMO, coupled components have two main drawbacks: difficult to maintain because changing one component may cause change to other coupled components; components cannot be used independently. 

In Yii2, the coupling is mostly caused by the inheritance. Therefore, if we have to take extra care when changing base classes (e.g. Component, Widget). As a result, if you use a component in your project, you would have to bring in the whole core framework. Unfortunately, this happens to most frameworks written in inheritance based OOP languages. There are ways to solve it, but often expensively and complicated for a scripting language like PHP. On the other hand, because Yii2 provides a highly cohesive experience, if you adopt it without thinking about replacing it with something else, it can greatly improve your productivity.

Go is a very interesting language. The composition-based OOP eliminates coupling caused by inheritance (PHP trait is similar but has some significant drawbacks, unfortunately). I wouldn't say using it would be as productive as using PHP for developing Web apps. However, it has broader use and great potential.

**Comment by su-xiaolin** [comment]
I am appreciate a lot for your answer, Thank you @qiangxue .
